##
##
## Docker Compose Config 
##
##

version: '2.0'

# Define network
networks:
  net_guacamole:
    driver: bridge

volumes:
  postgres-guacamole-data:

# Define services
services:
  # guacd
  guacd:
    container_name: ${PREFIX}-guacd
    image: guacamole/guacd
    networks:
      net_guacamole:
    restart: always

  # postgres
  postgres:
    container_name: ${PREFIX}-postgres-guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: guacamole_user
    #image: postgres:latest
    build: ./postgres
    networks:
      net_guacamole:
    restart: always
    volumes:
    - postgres-guacamole-data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: ${PREFIX}-guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      net_guacamole:
    ports:
    - 8080:8080/tcp
    restart: always
