##
##
## Docker Compose Config 
##
##

version: '2.0'

# Define network
networks:
  net_guacamole:
    driver: bridge

volumes:
  postgresql-guacamole-data:

# Define services
services:
  # guacd
  guacd:
    container_name: ${PREFIX}-guacd
    image: guacamole/guacd
    networks:
      net_guacamole:
    restart: always

  # postgresql
  postgresql:
    container_name: ${PREFIX}-postgresql-guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_USER: ${PSQL_USER}
    #image: postgres:latest
    build: ./postgresql
    networks:
      net_guacamole:
    restart: always
    volumes:
    - postgresql-guacamole-data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: ${PREFIX}-guacamole
    depends_on:
    - guacd
    - postgresql
    environment:
      GUACD_HOSTNAME: guacd
      EXTENSION_PRIORITY: ${EXTENSION_PRIORITY}
      POSTGRESQL_DATABASE: ${PSQL_DB}
      POSTGRESQL_HOSTNAME: postgresql
      POSTGRESQL_PASSWORD: ${PSQL_PASS}
      POSTGRESQL_USER: ${PSQL_USER}
      SAML_IDP_URL: ${SAML_IDP_URL}
      #SAML_IDP_METADATA_URL: ${SAML_IDP_METADATA_URL}
      SAML_ENTITY_ID: ${SAML_ENTITY_ID}
      SAML_CALLBACK_URL: ${SAML_CALLBACK_URL}
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      net_guacamole:
    ports:
    - 8080:8080/tcp
    restart: always
